[package]
name = "xgboost_lib-sys"
version = "0.1.0"
links = "xgboost"
build = "build.rs"
license = "MIT"
description = "Native bindings to the xgboost library"
readme = "README.md"
edition = "2021"

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = { version = "0.71" }
ureq = { version = "2.9", features = ["json"] }
zip = "2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"

[features]
default = []

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
